# Generated by Django 3.0.5 on 2020-04-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='nombre',
            new_name='last_name',
        ),
    ]
