# Generated by Django 3.0.5 on 2020-04-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_clasificacionesempresas_empresas_empresasmedidas_medidassanitarias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={},
        ),
    ]
