# Generated by Django 3.0.5 on 2020-05-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0010_clasificacionesempresas_empresas_empresasmedidas_medidassanitarias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': False},
        ),
    ]
