# Generated by Django 3.0.5 on 2020-05-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0011_auto_20200503_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpresasMedidas',
        ),
    ]
