# Generated by Django 3.0.5 on 2020-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0012_delete_empresasmedidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresasMedidas',
            fields=[
                ('cod_empresa_medida', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'empresas_medidas',
                'managed': False,
            },
        ),
    ]
